[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash -c 'uvicorn main:app --host 0.0.0.0 --port ${PORT:-8080}'"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[mount]
source = "/logs"
destination = "/app/logs"
