[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -c \"import os; from uvicorn import run; port = int(os.getenv('PORT', '8000')); run('main:app', host='0.0.0.0', port=port)\""
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[mount]
source = "/logs"
destination = "/app/logs"